---
title: "subIntro"
author: "Don Boyd"

---

# Possible approaches
Goal: Allocate as much of the federal budget as is practical – revenue and spending – to each of the individual 50 states, using “reasonable” methodologies.

Two possible approaches:

1. Foot the numbers to the federal budget – the formal data on receipts and disbursements, and the official budget deficit. Where data allow (rare), use actual information on how each component of the budget is distributed to individual states. In other cases “allocate” spending to individual states based on reasonable proxies.  (NOTE: When I use the term “federal budget” I am referring to a data source and a way of categorizing data. The term “budget” here does NOT mean that the numbers are budgeted or projected.) 
2. Use “disembodied” numbers from different data sources for major elements of the federal budget, and don’t worry too much if they do not add up to the federal budget precisely.

The attraction of the former is it allows us to get at the balance of payments concept but it forces us to come up with proxies to allocate the budget. The advantage of the latter is that it requires fewer assumptions, but then we don’t foot to the full budget. I believe the first approach is best for our purposes as long as we think we have reasonable proxies – an issue we currently are exploring.

## Authority, obligations or outlays?
Per the 1999 Moynihan report (p.109), "The dollar amounts reported by the Census Bureau in the CFFR report can represent either actual expenditures or obligations. As a general guide, the grants and procurement data in the CFFR report represent obligated funds, while the salaries, wages and direct payments show actual expenditures.""

## How the Moynihan report addressed this issue
Moynihan/KSG appear to have used a variant of #2: As far as I can tell, they added up all spending in CFFR, and treated that as the totality of federal spending, and then allocated a like amount of taxes (to force a balanced budget). That worked for them, I believe, because the CFFR accounted for about “four fifths” of federal outlays, per the 1999 fisc report. Per the Moynihan report:


* The calculations of Federal expenditures allocated to states are based on the reconciliation of two sources of data, the Consolidated Federal Funds Report, published by the Census Bureau, and the Budget of the United States Government, published by the Office of Management and Budget. While the Census Bureau does attempt to reconcile their data with the Federal budget, the two are not completely comparable. Over the past seven years, the Census measure of expenditures distributed domestically has accounted for about four fifths of total Federal outlays published by the Office of Management and Budget. Some areas of the budget, like foreign aid and some military spending, are spent overseas, so are not included in the Census data. No consistent methodology has been established to distribute other areas of spending such as net interest, deposit insurance or undistributed (by program) offsetting receipts. Finally, the amounts shown in the report for defense expenditures include all spending by the Department of Defense plus Department of Energy spending on defense-related activities and military retirement, disability payments, and other veterans’ benefits. (1999 Fisc Report, p.111)

## What Pew and NPP are doing
The National Priorities Project, and Pew, in their respective projects, are using the second approach. That is, they are not trying to add up to the full federal budget. This makes sense for their purposes because they are not comparing federal revenue to federal spending, and are not professing to allocate the entire federal budget to the 50 states.
